#!/usr/bin/env bash
# gen-catalog.sh — render docs/CATALOG.md from frontmatter (skills, agents, workflows,
# hooks) so prose never carries hand-maintained inventory.
#
#   scripts/gen-catalog.sh            # write docs/CATALOG.md
#   scripts/gen-catalog.sh --check    # exit 1 if CATALOG.md is stale, a /blitz:<name>
#                                     # reference points at no skill or workflow, or a
#                                     # numeric inventory claim appears in prose
set -euo pipefail
ROOT="${CLAUDE_PLUGIN_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$ROOT"
OUT="docs/CATALOG.md"
MODE="write"; [ "${1:-}" = "--check" ] && MODE="check"

fm() {  # fm <file> <key> — frontmatter scalar (single line), quotes stripped
  awk -v k="$2" 'NR==1 && $0 != "---" {exit} NR>1 && $0=="---" {exit} NR>1 && index($0, k":")==1 {sub("^" k ":[ ]*",""); gsub(/^"|"$/,""); print; exit}' "$1"
}
fm_desc() {  # description may be a block scalar (|) on agents: take first paragraph
  awk 'NR==1 && $0 != "---" {exit} NR>1 && $0=="---" {exit}
       /^description: *\|/ {blk=1; next}
       blk && /^  / {sub(/^  /,""); if ($0=="") exit; printf "%s ", $0; next}
       blk && !/^  / {exit}
       /^description:/ {sub(/^description:[ ]*/,""); gsub(/^"|"$/,""); print; exit}' "$1" | sed 's/ *$//' | cut -c1-240
}

render() {
  echo "# blitz catalog"
  echo
  echo "Generated by \`scripts/gen-catalog.sh\` from frontmatter. Do not edit by hand; run the script after adding, removing, or renaming a component."
  echo
  echo "## Skills"
  echo
  echo "| Skill | Invoke | Description |"
  echo "|---|---|---|"
  for f in skills/*/SKILL.md; do
    d=$(dirname "$f"); name=$(basename "$d")
    dmi=$(fm "$f" disable-model-invocation); hint=$(fm "$f" argument-hint)
    inv="/blitz:$name${hint:+ $hint}"; [ "$dmi" = "true" ] && inv="$inv (slash-only)"
    printf '| `%s` | `%s` | %s |\n' "$name" "$inv" "$(fm_desc "$f" | sed 's/|/\\|/g')"
  done
  echo
  echo "## Agents"
  echo
  echo "| Agent | Model | Tools | Description |"
  echo "|---|---|---|---|"
  for f in agents/*.md; do
    printf '| `%s` | %s | %s | %s |\n' "$(fm "$f" name)" "$(fm "$f" model)" "$(fm "$f" tools | sed 's/|/\\|/g')" "$(fm_desc "$f" | sed 's/|/\\|/g')"
  done
  echo
  echo "## Workflows"
  echo
  echo "| Workflow | Description |"
  echo "|---|---|"
  for f in workflows/*.js; do
    [ -f "$f" ] || continue
    n=$(grep -oE "name: *'[^']+'" "$f" | head -1 | sed "s/name: *'//; s/'//")
    d=$(grep -oE "description: *'[^']+'" "$f" | head -1 | sed "s/description: *'//; s/'//")
    printf '| `/blitz:%s` | %s |\n' "$n" "$d"
  done
  echo
  echo "## Hooks"
  echo
  echo "| Event | Matcher | Scripts |"
  echo "|---|---|---|"
  jq -r '.hooks | to_entries[] | .key as $ev | .value[] | "| \($ev) | \(.matcher // "*") | \([.hooks[].command | split("/") | last | split(" ")[0] | select(endswith(".sh"))] | unique | map("`" + . + "`") | join(", ")) |"' hooks/hooks.json
  echo
  echo "## Shared protocols"
  echo
  for f in skills/_shared/*.md; do
    t=$(grep -m1 '^# ' "$f" | sed 's/^# //')
    printf -- '- `%s`: %s\n' "$(basename "$f")" "${t:-$(basename "$f")}"
  done
}

if [ "$MODE" = "write" ]; then
  mkdir -p docs
  render > "$OUT"
  echo "wrote $OUT"
  exit 0
fi

rc=0
tmp=$(mktemp); render > "$tmp"
if ! diff -q "$tmp" "$OUT" >/dev/null 2>&1; then
  echo "gen-catalog: $OUT is stale; run scripts/gen-catalog.sh" >&2
  diff "$OUT" "$tmp" | head -20 >&2 || true
  rc=1
fi
rm -f "$tmp"

# Dead /blitz:<name> references (skills, workflows only; prose under docs/reviews and CHANGELOG is history)
known=$( { ls skills | grep -v '^_'; grep -ohE "name: *'[^']+'" workflows/*.js 2>/dev/null | sed "s/name: *'//; s/'//"; } | sort -u)
refs=$(grep -rhoE '/blitz:[a-z][a-z0-9-]*' --include=*.md --include=*.sh --include=*.js --include=*.json --include=*.yml --include=*.yaml \
  skills agents hooks scripts workflows evals templates README.md CLAUDE.md .claude .claude-plugin 2>/dev/null | sed 's#/blitz:##' | sort -u || true)
for r in $refs; do
  if ! printf '%s\n' "$known" | grep -qx "$r"; then
    echo "gen-catalog: dead reference /blitz:$r (no such skill or workflow); found in:" >&2
    grep -rlE "/blitz:$r([^a-z0-9-]|$)" --include=*.md --include=*.sh --include=*.js --include=*.json --include=*.yml skills agents hooks scripts workflows evals templates README.md CLAUDE.md .claude .claude-plugin 2>/dev/null | sed 's/^/  /' >&2
    rc=1
  fi
done

# Numeric inventory claims in prose
if grep -nE '\b[0-9]+ (skills?|agents?|hook scripts?|hooks?|events?|shared protocol files?|protocols?|detectors?)\b' README.md CLAUDE.md hooks/scripts/README.md .claude-plugin/plugin.json .claude-plugin/marketplace.json 2>/dev/null | grep -v 'CATALOG' ; then
  echo "gen-catalog: numeric inventory claim in prose (above); counts drift — describe, do not count" >&2
  rc=1
fi
[ "$rc" -eq 0 ] && echo "gen-catalog: OK"
exit "$rc"
